#!/usr/bin/env bash

# Copy paste from https://github.com/elm/compiler/blob/master/installers/linux/README.md
# for easy use in CI (since we need to install elm in our CI environment)

curl -L -o elm.gz https://github.com/elm/compiler/releases/download/0.19.1/binary-for-linux-64-bit.gz
gunzip elm.gz
chmod +x elm
sudo mv elm /usr/local/bin/
elm --help
