version: 2.1 # use CircleCI 2.1
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    docker: # run the steps with Docker
      - image: circleci/node:12.8.0 # ...with this image as the primary container; this is where all `steps` will run
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory
      # - run:
      #     name: Update npm
      #     command: 'sudo npm install -g npm@6.12.0'
      - run:
          name: Install elm-format
          command: 'sudo npm install elm-format'
      - run: # run tests
          name: Run elm-format
          command: elm-format frontend --validate
